[DEFAULT]
XRAY_BASE_URL="https://jira.talos.cisco.com/browse/"
BROWSER="Safari"
DOWNLOADS_FOLDER_PATH="/Users/admin/Downloads"
DOWNLOADING_DELAY=10
PRECONDITIONS_FILE_PATH="/Users/admin/Desktop/Work/Scripts/preconditions.txt"
FINAL_TEST_TYPE="Generic"
JIRA_API_URL="https://jira.talos.cisco.com/rest/api/2/"
TICKET_KEY="MAILSEC-13607"